## Rescaling Data

## Standardization Method

In [1]:
import pandas as pd
from sklearn import preprocessing
data = pd.read_csv('M7Stores.csv')
data = data[['Total_Customers', 'TotalSales']]
data.head()

Total_Customers  TotalSales
0              110       160.0
1              110       160.0
2               93       108.0
3              110       258.0
4              175       360.0

## Scale using sklearn

In [2]:

new_data=pd.DataFrame(preprocessing.scale(data))
new_data.head()

0         1
0 -0.543655 -0.579750
1 -0.543655 -0.579750
2 -0.795570 -1.006026
3 -0.543655  0.223615
4  0.419550  1.059772

## Slide 16

In [3]:
# normalize using sklearn
new_data=pd.DataFrame(preprocessing.normalize(data))
new_data.head()

0         1
0  0.566529  0.824042
1  0.566529  0.824042
2  0.652523  0.757769
3  0.392197  0.919881
4  0.437193  0.899368

## Slide 20, 21

In [4]:
data.head()

Total_Customers  TotalSales
0              110       160.0
1              110       160.0
2               93       108.0
3              110       258.0
4              175       360.0

In [5]:
data.head(15)

Total_Customers  TotalSales
0               110       160.0
1               110       160.0
2                93       108.0
3               110       258.0
4               175       360.0
5               105       225.0
6               245       360.0
7                62       146.7
8                95       140.8
9               123       167.6
10              123       167.6
11              180       275.8
12              180       275.8
13              180       275.8
14              205       472.0

In [6]:
data.tail()

Total_Customers  TotalSales
27              113        95.1
28              264       351.0
29              175       145.0
30              335       301.0
31              109       121.0

In [7]:
data.tail(10)

Total_Customers  TotalSales
22              150       304.0
23              245       350.0
24              175       400.0
25               66        79.0
26               91       120.3
27              113        95.1
28              264       351.0
29              175       145.0
30              335       301.0
31              109       121.0

## Slide 22 

In [8]:
data.describe()

Total_Customers  TotalSales
count        32.000000   32.000000
mean        146.687500  230.721875
std          68.562868  123.938694
min          52.000000   71.100000
25%          96.500000  120.825000
50%         123.000000  196.300000
75%         180.000000  326.000000
max         335.000000  472.000000

## Slide 26

In [12]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
data = asarray([['red'],['green'],['blue']])
data1 = asarray([['red'],['blue'],['green']])
print(data)

[['red']
 ['green']
 ['blue']]


In [13]:
#define ordinal encoding
encoder=OrdinalEncoder()
result=encoder.fit_transform(data)

result1=encoder.fit_transform(data1)
print(result)
print(result1)

[[2.]
 [1.]
 [0.]]
[[2.]
 [0.]
 [1.]]


In [14]:
from sklearn.preprocessing import OneHotEncoder
data = asarray([['red'],['green'],['blue']])
print(data)

[['red']
 ['green']
 ['blue']]


In [17]:
#define one hot encoding
encoder=OneHotEncoder()
result=encoder.fit_transform(data)
print(result.toarray())

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


## Slide 30

In [18]:
data=pd.DataFrame([['red'],['green'],['blue']])
print(data)

       0
0    red
1  green
2   blue


In [19]:
#define dummy encoding 
result=pd.get_dummies(data, drop_first=True)
print(result)

   0_green  0_red
0        0      1
1        1      0
2        0      0


In [20]:
# without drop first option the result is same as one hot encoding
result=pd.get_dummies(data)
print(result)

   0_blue  0_green  0_red
0       0        0      1
1       0        1      0
2       1        0      0


In [21]:
data = pd.read_csv('M7Stores.csv')
data = data[['Total_Customers', 'TotalSales']]
data.shape

(32, 2)

In [22]:
data.size

64

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from sklearn import datasets
iris=datasets.load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [25]:
y=iris.target
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [26]:
x=iris.data

In [34]:
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [35]:
clf=LinearRegression()
clf.fit(x_train,y_train)

LinearRegression()

In [36]:
y_pred=clf.predict(x_test)

In [32]:
mse=mean_squared_error(y_test,y_pred)

In [37]:
print("Mean Squared Error {}".format(mse))

Mean Squared Error 0.045091025799574545
