In [1]:
import pandas as pd
data = pd.read_csv('M6stores.csv')
data = data[['Total_Customers', 'TotalSales']]

# Mean

In [ ]:
# Mean using Pandas
data.mean()

In [3]:
# Mean using Numpy: Numpy flattens all data
data.to_numpy().mean()

188.70468749999998

In [4]:
# to get mean keeping rows we can pass axis attribute
data.to_numpy().mean(axis = 0)

array([146.6875  , 230.721875])

In [5]:
# using our own code: Take sum and divide by number of points
data.sum()/data.shape[0]

Total_Customers    146.687500
TotalSales         230.721875
dtype: float64

# Mode

In [6]:
# Finding mode using pandas
data.mode()

Total_Customers  TotalSales
0              110       275.8
1              175         NaN
2              180         NaN

In [7]:
# Finding mode using numpy
import numpy as np
vals, counts = np.unique(data.to_numpy(), return_counts=True, axis=0)
index = np.argmax(counts)
vals[index]

array([180. , 275.8])

In [8]:
# Finding the mode using scipy
from scipy import stats
stats.mode(data.to_numpy())

ModeResult(mode=array([[110. , 275.8]]), count=array([[3, 3]]))

# Median

In [9]:
# Using Pandas
data.median()

Total_Customers    123.0
TotalSales         196.3
dtype: float64

In [10]:
# using numpy
import numpy
numpy.median(data.to_numpy(), axis = 0)

array([123. , 196.3])

# Standard Deviation

In [11]:
data.std()

Total_Customers     68.562868
TotalSales         123.938694
dtype: float64

In [12]:
data.to_numpy().std(axis=0, ddof=1)

array([ 68.56286849, 123.93869383])

In [13]:
newData = data.to_numpy()
stddev = numpy.square(newData - newData.mean(axis = 0))
numpy.sqrt(stddev.sum(axis = 0)/(stddev.shape[0]-1))

array([ 68.56286849, 123.93869383])

# Variance

In [14]:
data.var()

Total_Customers     4700.866935
TotalSales         15360.799829
dtype: float64

In [15]:
data.to_numpy().var(axis=0, ddof=1)

array([ 4700.86693548, 15360.79982863])

In [16]:
newData = data.to_numpy()
stddev = numpy.square(newData - newData.mean(axis = 0))
stddev.sum(axis = 0)/(stddev.shape[0]-1)

array([ 4700.86693548, 15360.79982863])

# CoVariance

In [17]:
# using pandas
data.cov()

# covariance(Total_customer, Total_customer) = 4700.866935
# covariance(Total_customer, TotalSales) = 6721.158669
# covariance(TotalSales, TotalSales) = 15360.799829

Total_Customers    TotalSales
Total_Customers      4700.866935   6721.158669
TotalSales           6721.158669  15360.799829

In [18]:
numpy.cov(data.to_numpy().T)

array([[ 4700.86693548,  6721.15866935],
       [ 6721.15866935, 15360.79982863]])

# Correlation

In [19]:
data.corr(method='pearson')

Total_Customers  TotalSales
Total_Customers         1.000000    0.790949
TotalSales              0.790949    1.000000

In [20]:
data.corr(method='kendall')

Total_Customers  TotalSales
Total_Customers         1.000000    0.665999
TotalSales              0.665999    1.000000

In [21]:
data.corr(method='spearman')

Total_Customers  TotalSales
Total_Customers         1.000000    0.851043
TotalSales              0.851043    1.000000

In [22]:
numpy.corrcoef(data.to_numpy().T)

array([[1.        , 0.79094859],
       [0.79094859, 1.        ]])