In [22]:
import pandas as pd
from sklearn import preprocessing
data = pd.read_csv('stores.csv')
data = data[['Total_Customers', 'TotalSales']]
data.head()

Total_Customers  TotalSales
0              110       160.0
1              110       160.0
2               93       108.0
3              110       258.0
4              175       360.0

In [23]:
# normalize using sklearn
new_data = pd.DataFrame(preprocessing.scale(data))
new_data.head()

0         1
0 -0.543655 -0.579750
1 -0.543655 -0.579750
2 -0.795570 -1.006026
3 -0.543655  0.223615
4  0.419550  1.059772

In [24]:
new_data = pd.DataFrame(preprocessing.scale(data))
new_data.head()

0         1
0 -0.543655 -0.579750
1 -0.543655 -0.579750
2 -0.795570 -1.006026
3 -0.543655  0.223615
4  0.419550  1.059772

In [25]:
data.head(10)

Total_Customers  TotalSales
0              110       160.0
1              110       160.0
2               93       108.0
3              110       258.0
4              175       360.0
5              105       225.0
6              245       360.0
7               62       146.7
8               95       140.8
9              123       167.6

In [26]:
data.tail(10)

Total_Customers  TotalSales
22              150       304.0
23              245       350.0
24              175       400.0
25               66        79.0
26               91       120.3
27              113        95.1
28              264       351.0
29              175       145.0
30              335       301.0
31              109       121.0

In [27]:
data.describe()

Total_Customers  TotalSales
count        32.000000   32.000000
mean        146.687500  230.721875
std          68.562868  123.938694
min          52.000000   71.100000
25%          96.500000  120.825000
50%         123.000000  196.300000
75%         180.000000  326.000000
max         335.000000  472.000000

In [28]:
data.shape

(32, 2)

In [29]:
data.size

64

In [30]:
from sklearn.model_selection import train_test_split
train_feature,test_feature, train_target, test_target = train_test_split(data['Total_Customers'],data['TotalSales'],train_size=0.75,shuffle=True)
train_feature,val_feature, train_target, val_target = train_test_split(train_feature,train_target,train_size=0.75,shuffle=True)

In [1]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data = asarray([['red'], ['green'], ['blue']])
print(data)
# define ordinal encoding
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)
print(result)

[['red']
 ['green']
 ['blue']]
[[2.]
 [1.]
 [0.]]


In [3]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding
encoder = OneHotEncoder()
result = encoder.fit_transform(data)
print(result.toarray())

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [7]:
import pandas as pd

data = pd.DataFrame([['red'], ['green'], ['blue']])
print(data)
# define dummies encoding
result = pd.get_dummies(data, drop_first=True)
print(result)
# without drop first option the result is same as one hot encoding
result = pd.get_dummies(data)
print(result)

       0
0    red
1  green
2   blue
   0_green  0_red
0        0      1
1        1      0
2        0      0
   0_blue  0_green  0_red
0       0        0      1
1       0        1      0
2       1        0      0
